### ISSUE TITLE
Install Croupier infrastructure in APCLServer

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [ari-apc-lab/croupier#20]
Install Croupier infrastructure in APCLServer in Kubernetes cluster, including:
- Keycloak
- Vault, Vault Secret Loader,
- Cloudify/Croupier
- Frontend/Backend, adapted from Hidalgo

Ask @jramosrivas  for support from Grapevine

**Comment by jesus-gorronogoitia** [comment]
Kubernetes (microk8s) installed in APCLServer, following instructions: https://ubuntu.com/kubernetes/install

**Comment by jramosrivas** [comment]
Repo to host the k8s resource definitions is here:

https://github.com/ari-apc-lab/k8s-resources

**Comment by jesus-gorronogoitia** [comment]
Cloudify, Keycloak, Vault, Vault-Secret-Uploader installed in APCLServer using microk8s.

Endpoints: cloudify.croupier.permedcoe.eu, keycloak.croupier.permedcoe.eu, vault.croupier.permedcoe.eu, vault-secret-uploader..croupier.permedcoe.eu

Domain *.croupier.permedcoe.eu not yet registered in DNS, so this line in /etc/hosts is required for clients:
`62.14.219.13   cloudify.croupier.permedcoe.eu keycloak.croupier.permedcoe.eu vault.croupier.permedcoe.eu vault-secret-uploader.croupier.permedcoe.eu`
